Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2026
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2077
"GET /f/l HTTP/1.1" 301 0
hemo this 1st log
Internal Server Error: /f/l/
Traceback (most recent call last):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\GGhule\f drive\Logging\MyFistLog\firstlog\views.py", line 9, in flog
    return render(request,context)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
"GET /f/l/ HTTP/1.1" 500 118438
Not Found: /
"GET / HTTP/1.1" 404 2026
E:\GGhule\f drive\Logging\MyFistLog\MyFistLog\settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO hemo this 1st log
ERROR Internal Server Error: /f/l/
Traceback (most recent call last):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\GGhule\f drive\Logging\MyFistLog\firstlog\views.py", line 9, in flog
    return render(request,context)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR "GET /f/l/ HTTP/1.1" 500 118462
INFO Watching for file changes with StatReloader
INFO 2020-07-28 09:31:44,357 autoreload 12824 4480 Watching for file changes with StatReloader
WARNING 2020-07-28 09:31:46,346 log 12824 9140 Not Found: /
WARNING 2020-07-28 09:31:46,347 basehttp 12824 9140 "GET / HTTP/1.1" 404 2026
INFO 2020-07-28 09:31:53,810 views 12824 9140 hemo this 1st log
ERROR 2020-07-28 09:31:53,851 log 12824 9140 Internal Server Error: /f/l/
Traceback (most recent call last):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\GGhule\f drive\Logging\MyFistLog\firstlog\views.py", line 9, in flog
    return render(request,context)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR 2020-07-28 09:31:53,854 basehttp 12824 9140 "GET /f/l/ HTTP/1.1" 500 119186
INFO 2020-07-28 09:33:09,600 autoreload 13436 6732 Watching for file changes with StatReloader
